site_name: Prácticas Despliegue Aplicaciones web
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Open Sans
    code: Roboto Mono
  palette: 
        # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: deep purple
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: white
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - toc.integrate
    - navigation.footer
    - content.code.copy


markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  
  - admonition
  - pymdownx.details



extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Alexcoro13/Alexcoro13.github.io